name: build
on: [push]

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.6", "3.7", "3.8", "3.9"]

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        environment-file: pysb-conda-env.yml
        activate-environment: pysb
    - name: Conda environment info
      run: |
        conda info
        conda list
    - name: Test with pytest in macos
      if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
      shell: bash -l {0}
      run: |
        python -m pip
        sudo pip install coverage
        sudo pip install nose
    - name: Test with pytest in ubuntu and windows
      if: matrix.os == 'windows-latest'
      shell: bash -l {0}
      run: |
        python -m pip
        pip install coverage
        pip install nose
    - name: Build PySB
      run: python setup.py build --build-lib=build/lib
    - name: Run nosetests
      run: |
       python3 -m pip install sympy
       nosetests build/lib/pysb --with-coverage --cover-inclusive --cover-package=build/lib/pysb -a '!gpu'
